version: "3.8"

services:
  sigap-db:
    image: mysql:8.0
    container_name: sigap_it_database
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: sigap_it
    ports:
      - "3306:3306"
    volumes:
      - sigap_db_data:/var/lib/mysql

volumes:
  sigap_db_data:
